In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data=pd.read_csv('zomato.csv',encoding='latin-1')

In [5]:
data.shape

(9551, 21)

In [8]:
data.isnull().values.any()

True

In [5]:
data.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [6]:
data.drop(['Restaurant ID','Has Online delivery','Rating color', 'Rating text'],axis=1,inplace=True)

In [7]:
data.head()

Restaurant Name  Country Code              City  \
0        Le Petit Souffle           162       Makati City   
1        Izakaya Kikufuji           162       Makati City   
2  Heat - Edsa Shangri-La           162  Mandaluyong City   
3                    Ooma           162  Mandaluyong City   
4             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  Average Cost for two          Currency  \
0        French, Japanese, Desserts                  1100  Botswana Pula(P)   
1                          Japanese                  1200  Botswana Pula(P)   
2  Seafood, Asian, Filipino, Indian                  4000  Botswana Pula(P)   
3                   Japanese, Sushi                  1500  Botswana Pula(P)   
4                  Japanese, Korean                  1500  Botswana Pula(P)   

  Has Table booking Is delivering now Switch to order menu  Price range  \
0               Yes                No                   No            3   
1               Yes                No                   No            3   
2               Yes                No                   No            4   
3                No                No                   No            4   
4               Yes                No                   No            4   

   Aggregate rating  Votes  
0               4.8    314  
1               4.5    591  
2               4.4    270  
3               4.9    365  
4               4.8    229

In [8]:
data['Restaurant Name'].value_counts()

Cafe Coffee Day                     83
Domino's Pizza                      79
Subway                              63
Green Chick Chop                    51
McDonald's                          48
Keventers                           34
Pizza Hut                           30
Giani                               29
Baskin Robbins                      28
Barbeque Nation                     26
Dunkin' Donuts                      22
Giani's                             22
Barista                             22
Pind Balluchi                       20
Costa Coffee                        20
Wah Ji Wah                          19
Sagar Ratna                         19
Pizza Hut Delivery                  19
Twenty Four Seven                   19
KFC                                 18
Starbucks                           18
Chaayos                             18
Republic of Chicken                 18
Burger King                         16
Haldiram's                          16
Shree Rathnam            

In [9]:
data['Country Code'].value_counts()

1      8652
216     434
215      80
214      60
30       60
189      60
148      40
208      34
14       24
162      22
94       21
191      20
166      20
184      20
37        4
Name: Country Code, dtype: int64

In [10]:
data=data[data['Country Code']==1]

In [11]:
data.drop(['Country Code','Currency'],axis=1,inplace=True)

In [12]:
data.drop('Restaurant Name',axis=1,inplace=True)

In [13]:
data

City                                            Address  \
624        Agra  E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...   
625        Agra  E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...   
626        Agra        Main Market, Sadar Bazaar, Agra Cantt, Agra   
627        Agra  1/48, Delhi Gate, Station Road, Raja Mandi, Ci...   
628        Agra  23/453, Opposite Sanjay Cinema, Wazipura Road,...   
629        Agra  Courtyard by Marriott Agra, Phase 2, Fatehabad...   
630        Agra          ITC Mughal, Fatehabad Road, Tajganj, Agra   
631        Agra          ITC Mughal, Fatehabad Road, Tajganj, Agra   
632        Agra  3/20, KPS Tower, Near Tulsi Talkies, Bypass Ro...   
633        Agra    Radisson Blu, Taj East Gate Road, Tajganj, Agra   
634        Agra    Radisson Blu, Taj East Gate Road, Tajganj, Agra   
635        Agra  Meher Cinema Complex, Gwalior Road, Rakabganj,...   
636        Agra       Hotel Samovar, Fatehabad Road, Tajganj, Agra   
637        Agra  Opposite The Gateway Hotel, Fatehabad Road, Ta...   
638        Agra  Parador Hotel, 3A-3B, Phase 1, Fatehabad Road,...   
639        Agra  1374 K/1375 K, 2nd floor, Dinesh Nagar, Fatehb...   
640        Agra  Opposite Saga Emporium, Fatehabad Road, Tajgan...   
641        Agra  8, Handicraft Nagar, Fatehabad Road, Tajganj, ...   
642        Agra  Near Purani Mandi Crossing,Fatehabad Road, Taj...   
643        Agra  Next To ITC Mughal Hotel, Fatehabad Road, Tajg...   
644   Ahmedabad  Shreekunj Mandapam, Beside Golden Tulip Bunglo...   
645   Ahmedabad  Chinubhai Tower, Nehru Bridge Corner, Ashram R...   
646   Ahmedabad  7 B, Circle  B, Opposite Rajpath Club, Sarkhej...   
647   Ahmedabad        Opposite Sindhu Bhawan, Bodakdev, Ahmedabad   
648   Ahmedabad  Ground Floor, Maruti Crystal, Opposite Rajpath...   
649   Ahmedabad  Shop 10,  Circle B, Nyay Marg, Bodakdev, Ahmed...   
650   Ahmedabad  6-9, Ground Floor, Devashish Business Park, Op...   
651   Ahmedabad  10th Floor, Balaji Heights Buliding, Behind Ta...   
652   Ahmedabad  Courtyard By Marriott, Ramdevnagar Cross Road,...   
653   Ahmedabad  Ground Floor, Arjun Avenue, Opposite Samarthes...   
...         ...                                                ...   
9246   Varanasi  1st Floor, Swastik Plaza, Near Ravidas Gate, B...   
9247   Varanasi           34-B, Ravindra Puri, Near Lanka,Varanasi   
9248   Varanasi  S 19/1 K, Mint House, Near Hotel Taj, Nai Baza...   
9249   Varanasi         Near Sbi Atm, Main Road, Nadesar, Varanasi   
9250   Varanasi   Radisson Hotel, The Mall Road, Nadesar, Varanasi   
9251   Varanasi   Radisson Hotel, The Mall Road, Nadesar, Varanasi   
9252   Varanasi               B 3/335, Krimkund, Shivala, Varanasi   
9253   Varanasi  5th Floor Roof Top,(Above Big Bazaar) Sigra. O...   
9254   Varanasi  Hotel Varuna Ground Floor, 22 Gulab Bagh, Sigr...   
9255   Varanasi  1st Floor, Nath Complex, Beside Life Line Hosp...   
9256      Vizag  52-1-35,36&38, CMR Mall, New Resapavanipalem, ...   
9257      Vizag  Plot No 47- 10-23/3, 5th Floor, Isnar Khazana ...   
9258      Vizag  Diamond Park, Railway New Colony Road, Dwaraka...   
9259      Vizag  Hotel GreenPark, Waltair Main Road, Waltair Up...   
9260      Vizag    Hotel Novotel, Beach Road, Maharani Peta, Vizag   
9261      Vizag  28-10-33/6, Jagdamba Commercial Complex, Chitr...   
9262      Vizag  1st Floor, ATR Towers, Harbour Park Road,  Pan...   
9263      Vizag  Ground Floor, ATR Towers, Harbour Park Road, P...   
9264      Vizag   4-70-4, Opposite NCC Canteen, Lawsons Bay, Vizag   
9265      Vizag  Beach Road, Near Santhi Ashram, Lawsons Bay, V...   
9266      Vizag  HB Colony, Isukathota, National Highway 5, Bes...   
9267      Vizag  RK Beach, Maharani Peta, Vizag Visakhapatnam.,...   
9268      Vizag  7-5-82, Sea Shore Apartments, Southern Portion...   
9269      Vizag  1-83-29, Opposite Pollock Lotus School, MVP Do...   
9270      Vizag  Beach Road, Opposite Cyclone Shelter ,   Visak...   
9271      Vizag  Beac

In [14]:
data['City'].value_counts().head(4)

New Delhi    5473
Gurgaon      1118
Noida        1080
Faridabad     251
Name: City, dtype: int64

In [15]:
city=['New Delhi','Gurgaon','Noida','Faridabad']

In [16]:
data=data[data['City'].isin(city)]

In [17]:
data.shape

(7922, 14)

In [18]:
data['City'].value_counts()

New Delhi    5473
Gurgaon      1118
Noida        1080
Faridabad     251
Name: City, dtype: int64

In [19]:
data.columns

Index(['City', 'Address', 'Locality', 'Locality Verbose', 'Longitude',
       'Latitude', 'Cuisines', 'Average Cost for two', 'Has Table booking',
       'Is delivering now', 'Switch to order menu', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [20]:
data.drop(['Address','Locality','Locality Verbose'],axis=1,inplace=True)

/home/saurabh/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [21]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [22]:
data['Has Table booking'].replace({'No':0,'Yes':1},inplace=True)

/home/saurabh/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [23]:
data['Has Table booking'].value_counts()

0    6876
1    1046
Name: Has Table booking, dtype: int64

In [24]:
data['Has Online delivery'].replace({'No':0,'Yes':1},inplace=True)

KeyError: 'Has Online delivery'

In [25]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [26]:
data.drop('Switch to order menu',axis=1,inplace=True)

In [27]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [28]:
data.corr()['Average Cost for two']

Longitude               0.071752
Latitude                0.070993
Average Cost for two    1.000000
Has Table booking       0.642966
Price range             0.847985
Aggregate rating        0.328440
Votes                   0.299089
Name: Average Cost for two, dtype: float64

In [29]:
data.head()

City  Longitude   Latitude                    Cuisines  \
865  Faridabad  77.306640  28.490059  Chinese, Fast Food, Bakery   
866  Faridabad  77.304776  28.490157       North Indian, Chinese   
867  Faridabad  77.305563  28.490137                North Indian   
868  Faridabad  77.306102  28.490098                North Indian   
869  Faridabad  77.305745  28.490062                      Bakery   

     Average Cost for two  Has Table booking Is delivering now  Price range  \
865                   250                  0                No            1   
866                   500                  0                No            2   
867                   150                  0                No            1   
868                   150                  0                No            1   
869                   100                  0                No            1   

     Aggregate rating  Votes  
865               2.9      4  
866               2.8     16  
867               2.8      8  
868               2.9      8  
869               2.8      7

In [30]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [31]:
data.drop('Is delivering now',axis=1,inplace=True)

In [32]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [33]:
data.head()

City  Longitude   Latitude                    Cuisines  \
865  Faridabad  77.306640  28.490059  Chinese, Fast Food, Bakery   
866  Faridabad  77.304776  28.490157       North Indian, Chinese   
867  Faridabad  77.305563  28.490137                North Indian   
868  Faridabad  77.306102  28.490098                North Indian   
869  Faridabad  77.305745  28.490062                      Bakery   

     Average Cost for two  Has Table booking  Price range  Aggregate rating  \
865                   250                  0            1               2.9   
866                   500                  0            2               2.8   
867                   150                  0            1               2.8   
868                   150                  0            1               2.9   
869                   100                  0            1               2.8   

     Votes  
865      4  
866     16  
867      8  
868      8  
869      7

In [34]:
data['Cuisines'].value_counts()

North Indian                                                           901
North Indian, Chinese                                                  474
Fast Food                                                              330
Chinese                                                                323
North Indian, Mughlai                                                  313
Cafe                                                                   251
Bakery                                                                 212
North Indian, Mughlai, Chinese                                         194
Bakery, Desserts                                                       168
Street Food                                                            145
Pizza, Fast Food                                                       126
Chinese, Fast Food                                                     117
Mithai, Street Food                                                    116
Bakery, Fast Food        

In [35]:
 cuisine=data.groupby('Cuisines').mean()['Average Cost for two'].reset_index()

In [36]:
data=data.merge(cuisine,on='Cuisines')

In [37]:
data.drop('Cuisines',axis=1,inplace=True)

In [38]:
data

City  Longitude   Latitude  Average Cost for two_x  \
0     Faridabad  77.306640  28.490059                     250   
1     New Delhi  77.049525  28.806199                     500   
2     Faridabad  77.304776  28.490157                     500   
3     Faridabad   0.000000   0.000000                     300   
4     Faridabad  77.305698  28.471985                    1200   
5     Faridabad  77.292278  28.398268                     400   
6     Faridabad  77.329161  28.375486                     450   
7     Faridabad  77.328898  28.377754                     700   
8     Faridabad  77.318483  28.371951                     450   
9     Faridabad  77.314446  28.381192                     550   
10    Faridabad   0.000000   0.000000                     400   
11    Faridabad  77.322930  28.395009                     600   
12    Faridabad  77.318577  28.410708                     400   
13    Faridabad  77.328898  28.410603                     600   
14    Faridabad  77.313820  28.417529                     200   
15    Faridabad  77.315951  28.454997                     300   
16    Faridabad  77.310500  28.480467                    1000   
17    Faridabad  77.311397  28.480552                     300   
18    Faridabad  77.311487  28.480829                     300   
19    Faridabad  77.305606  28.480730                     500   
20    Faridabad   0.000000   0.000000                     600   
21    Faridabad   0.000000   0.000000                     300   
22    Faridabad  77.325997  28.363899                     250   
23    Faridabad  77.328539  28.368654                     500   
24    Faridabad  77.336451  28.408678                     650   
25    Faridabad  77.342313  28.412268                     500   
26    Faridabad  77.336292  28.410219                     500   
27    Faridabad  77.293759  28.498215                     500   
28    Faridabad  77.293041  28.499223                     600   
29      Gurgaon  77.078058  28.432548                     300   
...         ...        ...        ...                     ...   
7892      Noida  77.361828  28.569250                     500   
7893      Noida  77.360975  28.561503                     600   
7894      Noida  77.362094  28.569279                     500   
7895      Noida   0.000000   0.000000                     500   
7896      Noida  77.361977  28.570281                     400   
7897      Noida  77.362309  28.570602                     550   
7898      Noida  77.369364  28.578298                     600   
7899      Noida   0.000000   0.000000                     300   
7900      Noida  77.374547  28.581684                     100   
7901      Noida   0.000000   0.000000                     500   
7902      Noida  77.366121  28.581868                     550   
7903      Noida  77.362594  28.595375                     600   
7904      Noida  77.365506  28.591384                     500   
7905      Noida  77.362456  28.612791                     500   
7906      Noida   0.000000   0.000000                     500   
7907      Noida  77.382379  28.564510                     400   
7908      Noida  77.381327  28.566393                     350   
7909      Noida  77.392072  28.571730                     500   
7910      Noida  77.380397  28.589199                     250   
7911      Noida  77.400003  28.588073                     500   
7912      Noida  77.334697  28.541939                     500   
7913      Noida  77.380418  28.571616                     600   
7914      Noida  77.385331  28.514600                     200   
7915      Noida  77.341371  28.586239                    1300   
7916      Noida  77.337325  28.583579                     500   
7917      Noida  77.341021  28.585493                    2500   
7918      Noida  77.364833  28.597103                     200   
7919      Noida  77.364833  28.597103                     450   
7920      Noida  77.323213  28.567751                    1000   
7921      Noida  77.325308  28.567150         

In [39]:
y=data.iloc[:,3].values

In [40]:
y

array([ 250,  500,  500, ...,  450, 1000,  450])

In [41]:
dataX=data.drop('Average Cost for two_x',axis=1)

In [42]:
dataX

City  Longitude   Latitude  Has Table booking  Price range  \
0     Faridabad  77.306640  28.490059                  0            1   
1     New Delhi  77.049525  28.806199                  0            2   
2     Faridabad  77.304776  28.490157                  0            2   
3     Faridabad   0.000000   0.000000                  0            1   
4     Faridabad  77.305698  28.471985                  1            3   
5     Faridabad  77.292278  28.398268                  0            1   
6     Faridabad  77.329161  28.375486                  0            1   
7     Faridabad  77.328898  28.377754                  1            2   
8     Faridabad  77.318483  28.371951                  0            1   
9     Faridabad  77.314446  28.381192                  0            2   
10    Faridabad   0.000000   0.000000                  0            1   
11    Faridabad  77.322930  28.395009                  0            2   
12    Faridabad  77.318577  28.410708                  0            1   
13    Faridabad  77.328898  28.410603                  0            2   
14    Faridabad  77.313820  28.417529                  0            1   
15    Faridabad  77.315951  28.454997                  0            1   
16    Faridabad  77.310500  28.480467                  1            3   
17    Faridabad  77.311397  28.480552                  0            1   
18    Faridabad  77.311487  28.480829                  0            1   
19    Faridabad  77.305606  28.480730                  0            2   
20    Faridabad   0.000000   0.000000                  0            2   
21    Faridabad   0.000000   0.000000                  0            1   
22    Faridabad  77.325997  28.363899                  0            1   
23    Faridabad  77.328539  28.368654                  0            2   
24    Faridabad  77.336451  28.408678                  0            2   
25    Faridabad  77.342313  28.412268                  0            2   
26    Faridabad  77.336292  28.410219                  0            2   
27    Faridabad  77.293759  28.498215                  0            2   
28    Faridabad  77.293041  28.499223                  0            2   
29      Gurgaon  77.078058  28.432548                  0            1   
...         ...        ...        ...                ...          ...   
7892      Noida  77.361828  28.569250                  0            2   
7893      Noida  77.360975  28.561503                  0            2   
7894      Noida  77.362094  28.569279                  0            2   
7895      Noida   0.000000   0.000000                  0            2   
7896      Noida  77.361977  28.570281                  0            1   
7897      Noida  77.362309  28.570602                  0            2   
7898      Noida  77.369364  28.578298                  0            2   
7899      Noida   0.000000   0.000000                  0            1   
7900      Noida  77.374547  28.581684                  0            1   
7901      Noida   0.000000   0.000000                  0            2   
7902      Noida  77.366121  28.581868                  0            2   
7903      Noida  77.362594  28.595375                  0            2   
7904      Noida  77.365506  28.591384                  0            2   
7905      Noida  77.362456  28.612791                  0            2   
7906      Noida   0.000000   0.000000                  0            2   
7907      Noida  77.382379  28.564510                  0            1   
7908      Noida  77.381327  28.566393                  0            1   
7909      Noida  77.392072  28.571730                  0            2   
7910      Noida  77.380397  28.589199                  0            1   
7911      Noida  77.400003  28.588073                  0            2   
7912      Noida  77.334697  28.541939                  0            2   
7913      Noida  77.380418  28.571616                  0            2   
7914      Noida  77.385331  28.514600                  0            1

In [43]:
X=dataX.iloc[:,:].values

In [44]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [45]:
X[:,0]=encoder.fit_transform(X[:,0])

In [46]:
X

array([[0, 77.3066401, 28.4900591, ..., 2.9, 4, 375.0],
       [2, 77.04952508, 28.80619877, ..., 0.0, 0, 375.0],
       [0, 77.304776, 28.490156699999996, ..., 2.8, 16,
        594.3037974683544],
       ...,
       [3, 77.3648332, 28.5971027, ..., 3.5, 105, 450.0],
       [3, 77.32321292, 28.567750899999997, ..., 0.0, 0, 1000.0],
       [3, 77.32530809999999, 28.5671503, ..., 2.0, 161, 450.0]],
      dtype=object)

In [47]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categorical_features=[0])

In [48]:
X=ohe.fit_transform(X).toarray()

/home/saurabh/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/saurabh/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [49]:
X[0]

array([  1.       ,   0.       ,   0.       ,   0.       ,  77.3066401,
        28.4900591,   0.       ,   1.       ,   2.9      ,   4.       ,
       375.       ])

In [50]:
X=X[:,1:]

In [51]:
X[0]

array([  0.       ,   0.       ,   0.       ,  77.3066401,  28.4900591,
         0.       ,   1.       ,   2.9      ,   4.       , 375.       ])

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [53]:
X_train.shape

(6337, 10)

In [54]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [55]:
LinearRegression(copy_X=True,fit_intercept=True,n_jobs=None,normalize=False)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [56]:
y_pred=regressor.predict(X_test)

In [57]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8210945205245264

In [58]:
X_test[0]

array([  0.        ,   1.        ,   0.        ,  77.1390339 ,
        28.7052961 ,   0.        ,   1.        ,   2.9       ,
         9.        , 547.05882353])

In [59]:
y_test[800]

800

In [60]:
regressor.predict(X_test[800].reshape(1,10))

array([860.40982731])